services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    networks:
      - flask-network
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 120s

  flask_app:
    image: flask_app:0.1
    build:
      context: .
      dockerfile: Dockerfile-compose
    container_name: flask_app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${API_PORT}:5000"
    networks:
      - flask-network

networks:
  flask-network:
    name: flask-network
    driver: bridge