name: Build flask app docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: login docker registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: Build
      run: docker build . -t ghcr.io/${{ github.actor }}/aventus_exersice_1:${TAG}
    - name: Push
      run: |
        TAG=$(cat VERSION)
        docker push ghcr.io/${{ github.actor }}/aventus_exersice_1:${TAG}
