name: Build flask app docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: 0.1

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: login to the docker registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      run: |
        docker build . -t ${{ env.REGISTRY }}/${{ github.actor }}/bot:${{ env.TAG }}
        docker push ${{ env.REGISTRY }}/${{ github.actor }}/bot:${{ env.TAG }}
